- hosts: localhost
  become: yes
  become_method: sudo
  connection: local

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
    - "group_vars/{{ env }}.yaml"

  roles:
    - base
    - php
    - web
    - database
    - app
